spring.application.name: groupshare

server:
  port: 9090

spring:
  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB
  datasource:
    url: jdbc:postgresql://localhost:5432/groupshare
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

minio:
  url: "http://127.0.0.1:9000"
  accessKey: minioadmin
  secretKey: minioadmin